version: '3.8'

services:
  # Eureka Service Registry
  eureka-server:
    build:
      context: ./Ace-Eureka
    ports:
      - "8761:8761"
    container_name: ace-eureka
    networks:
      - ace-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    restart: always

  # Gateway Service
  gateway-service:
    build:
      context: ./Ace-Gateway
    ports:
      - "8080:8080"
    container_name: ace-gateway
    networks:
      - ace-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://ace-eureka:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    restart: always

  # Vehicle Service
  vehicle-service:
    build:
      context: ./VehicleService
    ports:
      - "8081:8081"
    container_name: vehicle-service
    networks:
      - ace-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://ace-eureka:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://vehicle-db:3306/vehicle_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  # User Service
  user-service:
    build:
      context: ./UserService
    ports:
      - "8082:8082"
    container_name: user-service
    networks:
      - ace-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://ace-eureka:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/user_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  # Alert Service
  alert-service:
    build:
      context: ./AlertService
    ports:
      - "8083:8083"
    container_name: alert-service
    networks:
      - ace-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://ace-eureka:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://alert-db:3306/alert_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  # Anomaly Detection Service
  anomaly-detection-service:
    build:
      context: ./AnomalyDetectionService
    ports:
      - "5000:5000"
    container_name: anomaly-detection-service
    networks:
      - ace-network
    depends_on:
      - vehicle-service
    restart: always

  # MySQL for Vehicle Service
  vehicle-db:
    image: mysql:8
    container_name: vehicle-db
    networks:
      - ace-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vehicle_service
    ports:
      - "3307:3306"

  # MySQL for User Service
  user-db:
    image: mysql:8
    container_name: user-db
    networks:
      - ace-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_service
    ports:
      - "3308:3306"

  # MySQL for Alert Service
  alert-db:
    image: mysql:8
    container_name: alert-db
    networks:
      - ace-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alert_service
    ports:
      - "3309:3306"

  # Angular Frontend
  ace-frontend:
    build:
      context: ./AceFrontend
    ports:
      - "4200:4200"
    container_name: ace-frontend
    networks:
      - ace-network
    depends_on:
      - gateway-service
    restart: always
    environment:
      - NG_PROXY=http://gateway-service:8080 # Proxy to backend gateway

networks:
  ace-network:
    driver: bridge
