server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  
  application:
    name: ace-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
logging:
  level:
    root: DEBUG
